image: pandoc/latex:latest

on:
  push:
    branches:
      - main
  workflow_dispatch:          # This enables manual triggering

only:
  - master

concurrency:
  group: pages-build          # Name for the group of workflows to control concurrency
  cancel-in-progress: true    # Cancel any currently running workflow if a new one starts

pages:
  script:
    - mkdir public
    - pandoc -f markdown -t html README.md -o public/index.html
  artifacts:
    paths:
      - public
